# Generated by Django 3.0.2 on 2020-02-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_name', models.CharField(max_length=255, verbose_name='Habit Name')),
                ('goal', models.CharField(max_length=255, verbose_name='Goal')),
                ('start_date', models.DateField(verbose_name='Start date')),
            ],
        ),
        migrations.CreateModel(
            name='SmallGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=255, verbose_name='Small Goal')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.Habit', verbose_name='Habit')),
            ],
        ),
    ]
